[package]
name = "telegram-bot-send"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
] } # HTTP 客户端
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
